"""Tests for the LM-T0 pre-cutover Alembic migration.

REQ: wealth migration pre-cutover widening (LM-T0).

Covers:
- Upgrade: changed_by widened to String(64), cf_scheduled_time added,
  plaid_item CHECK accepts 'pending_oauth' and 'abandoned'.
- Downgrade: changes reversed; downgrade is refused when 'pending_oauth'
  or 'abandoned' rows exist.
- Round-trip: upgrade → downgrade → upgrade on a fixture DB leaves the
  schema consistent.

Technique mirrors ``src/db/test_phase4_extend_enums_migration.py``:
use ``_stamp_at`` to create only the tables the migration touches,
skip running all prior migrations from scratch (which would fail because
historical autogenerated migrations assume pre-existing tables).
"""

from __future__ import annotations

import os
import uuid
from datetime import UTC, datetime
from pathlib import Path

import pytest
import sqlalchemy as sa

# ---------------------------------------------------------------------------
# Revision identifiers
# ---------------------------------------------------------------------------
_PREV_REV = "plaid_p1_init_6a9b"
_THIS_REV = "lmt0_wealth_pre_cutover"

# ---------------------------------------------------------------------------
# DDL for the two tables this migration touches (at the _PREV_REV schema).
# ---------------------------------------------------------------------------

_AUDIT_EVENTS_DDL = """
CREATE TABLE audit_events (
    id VARCHAR NOT NULL,
    transaction_id VARCHAR,
    field_changed VARCHAR NOT NULL,
    old_value TEXT,
    new_value TEXT,
    changed_by VARCHAR(8) NOT NULL,
    changed_at DATETIME NOT NULL,
    entity_id VARCHAR(36),
    entity_type VARCHAR(32),
    PRIMARY KEY (id),
    CONSTRAINT ck_audit_events_exactly_one_target CHECK (
        (transaction_id IS NOT NULL AND entity_id IS NULL AND entity_type IS NULL)
        OR (transaction_id IS NULL AND entity_id IS NOT NULL AND entity_type IS NOT NULL)
    )
)
"""

_PLAID_ITEM_DDL = """
CREATE TABLE plaid_item (
    id VARCHAR(36) NOT NULL,
    item_id VARCHAR(128) NOT NULL,
    institution_id VARCHAR(64) NOT NULL,
    institution_name VARCHAR(128) NOT NULL,
    access_token_encrypted TEXT NOT NULL,
    cursor VARCHAR(255),
    last_sync_at DATETIME,
    last_sync_status VARCHAR(24),
    last_error VARCHAR(64),
    consent_expiration_at DATETIME,
    state_nonce VARCHAR(64),
    state_nonce_expires_at DATETIME,
    status VARCHAR(16) DEFAULT 'active' NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_plaid_item_item_id UNIQUE (item_id),
    CONSTRAINT ck_plaid_item_status CHECK (status IN ('active', 'disconnected')),
    CONSTRAINT ck_plaid_item_last_sync_status CHECK (
        last_sync_status IS NULL
        OR last_sync_status IN ('ok', 'error', 'pending', 'institution_down')
    )
)
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _run_alembic(*args: str) -> None:
    """Invoke Alembic using alembic.config.main — picks up DATABASE_PATH from env."""
    from alembic.config import main as alembic_main

    alembic_main(list(args))


def _stamp_at(db_path: Path, revision: str) -> None:
    """Create a fresh fixture DB stamped at *revision*.

    Creates only the tables the LM-T0 migration touches (audit_events and
    plaid_item), stamps the alembic_version table at *revision*, and sets
    DATABASE_PATH in the process environment so subsequent _run_alembic calls
    use this fixture DB.
    """
    os.environ["DATABASE_PATH"] = str(db_path)
    engine = sa.create_engine(f"sqlite:///{db_path}")
    with engine.begin() as conn:
        conn.execute(
            sa.text(
                "CREATE TABLE alembic_version (version_num VARCHAR(32) NOT NULL,"
                " CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num))"
            )
        )
        conn.execute(sa.text(f"INSERT INTO alembic_version VALUES ('{revision}')"))
        conn.execute(sa.text(_AUDIT_EVENTS_DDL))
        conn.execute(sa.text(_PLAID_ITEM_DDL))
    engine.dispose()


def _table_info(db_path: Path, table: str) -> dict[str, dict]:
    """Return {column_name: {type, notnull}} for *table* in the fixture DB."""
    engine = sa.create_engine(f"sqlite:///{db_path}")
    with engine.connect() as conn:
        rows = conn.execute(sa.text(f"PRAGMA table_info({table})")).fetchall()
    engine.dispose()
    return {r[1]: {"type": r[2], "notnull": r[3]} for r in rows}


def _table_ddl(db_path: Path, table: str) -> str:
    engine = sa.create_engine(f"sqlite:///{db_path}")
    with engine.connect() as conn:
        row = conn.execute(
            sa.text("SELECT sql FROM sqlite_master WHERE type='table' AND name=:t"),
            {"t": table},
        ).fetchone()
    engine.dispose()
    return row[0] if row else ""


def _now() -> datetime:
    return datetime.now(UTC).replace(tzinfo=None)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def fixture_db(tmp_path: Path) -> Path:
    """Fresh fixture DB stamped at the revision before LM-T0."""
    db_path = tmp_path / "test_lmt0.db"
    _stamp_at(db_path, _PREV_REV)
    return db_path


# ---------------------------------------------------------------------------
# Upgrade tests
# ---------------------------------------------------------------------------


class TestUpgrade:
    """LM-T0 upgrade produces the expected schema changes."""

    def test_upgrade_changes_rev(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.connect() as conn:
            rev = conn.execute(
                sa.text("SELECT version_num FROM alembic_version")
            ).scalar_one()
        engine.dispose()
        assert rev == _THIS_REV

    def test_changed_by_widened_to_64(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        cols = _table_info(fixture_db, "audit_events")
        assert "changed_by" in cols
        assert "64" in cols["changed_by"]["type"].upper()

    def test_cf_scheduled_time_column_exists(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        cols = _table_info(fixture_db, "audit_events")
        assert "cf_scheduled_time" in cols
        assert cols["cf_scheduled_time"]["notnull"] == 0  # nullable

    def test_cf_scheduled_time_bigint(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        cols = _table_info(fixture_db, "audit_events")
        assert "BIGINT" in cols["cf_scheduled_time"]["type"].upper()

    def test_plaid_item_check_accepts_pending_oauth(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO plaid_item"
                    " (id, item_id, institution_id, institution_name,"
                    "  access_token_encrypted, status, created_at, updated_at)"
                    " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                    "  'tok_enc', 'pending_oauth', :now, :now)"
                ),
                {"id": row_id, "item_id": "item-po-1", "now": _now()},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT status FROM plaid_item WHERE id = :id"),
                {"id": row_id},
            ).scalar_one()
        engine.dispose()
        assert result == "pending_oauth"

    def test_plaid_item_check_accepts_abandoned(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO plaid_item"
                    " (id, item_id, institution_id, institution_name,"
                    "  access_token_encrypted, status, created_at, updated_at)"
                    " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                    "  'tok_enc', 'abandoned', :now, :now)"
                ),
                {"id": row_id, "item_id": "item-ab-1", "now": _now()},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT status FROM plaid_item WHERE id = :id"),
                {"id": row_id},
            ).scalar_one()
        engine.dispose()
        assert result == "abandoned"

    def test_plaid_item_check_rejects_invalid_status(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with pytest.raises(sa.exc.IntegrityError):  # CHECK constraint violation  # noqa: SIM117
            with engine.begin() as conn:
                conn.execute(
                    sa.text(
                        "INSERT INTO plaid_item"
                        " (id, item_id, institution_id, institution_name,"
                        "  access_token_encrypted, status, created_at, updated_at)"
                        " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                        "  'tok_enc', 'bogus_status', :now, :now)"
                    ),
                    {"id": str(uuid.uuid4()), "item_id": "item-bad", "now": _now()},
                )
        engine.dispose()

    def test_long_changed_by_accepted(self, fixture_db: Path) -> None:
        """changed_by accepts a 23-char cron actor string after widening to 64."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        tx_id = str(uuid.uuid4())
        long_actor = "cron:twelve-data-ingest"  # 23 chars — exceeds old String(8)
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO audit_events"
                    " (id, transaction_id, field_changed, changed_by, changed_at)"
                    " VALUES (:id, :tx, 'price_refresh', :actor, :now)"
                ),
                {"id": row_id, "tx": tx_id, "actor": long_actor, "now": _now()},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT changed_by FROM audit_events WHERE id = :id"),
                {"id": row_id},
            ).scalar_one()
        engine.dispose()
        assert result == long_actor

    def test_human_email_changed_by_accepted(self, fixture_db: Path) -> None:
        """changed_by accepts a 'human:<email>' string (>8 chars)."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        tx_id = str(uuid.uuid4())
        email_actor = "human:travis@sparkry.com"
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO audit_events"
                    " (id, transaction_id, field_changed, changed_by, changed_at)"
                    " VALUES (:id, :tx, 'status', :actor, :now)"
                ),
                {"id": row_id, "tx": tx_id, "actor": email_actor, "now": _now()},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT changed_by FROM audit_events WHERE id = :id"),
                {"id": row_id},
            ).scalar_one()
        engine.dispose()
        assert result == email_actor

    def test_cf_scheduled_time_defaults_null(self, fixture_db: Path) -> None:
        """Rows inserted without cf_scheduled_time have NULL in that column."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        tx_id = str(uuid.uuid4())
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO audit_events"
                    " (id, transaction_id, field_changed, changed_by, changed_at)"
                    " VALUES (:id, :tx, 'field', 'human', :now)"
                ),
                {"id": row_id, "tx": tx_id, "now": _now()},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT cf_scheduled_time FROM audit_events WHERE id = :id"),
                {"id": row_id},
            ).scalar_one_or_none()
        engine.dispose()
        assert result is None

    def test_cf_scheduled_time_stores_epoch_ms(self, fixture_db: Path) -> None:
        """cf_scheduled_time stores Unix epoch milliseconds correctly."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        row_id = str(uuid.uuid4())
        tx_id = str(uuid.uuid4())
        epoch_ms = 1747872000000  # 2026-05-21T19:20:00Z in ms
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO audit_events"
                    " (id, transaction_id, field_changed, changed_by,"
                    "  changed_at, cf_scheduled_time)"
                    " VALUES (:id, :tx, 'price_refresh', 'cron:twelve-data-ingest',"
                    "  :now, :epoch_ms)"
                ),
                {"id": row_id, "tx": tx_id, "now": _now(), "epoch_ms": epoch_ms},
            )
        with engine.connect() as conn:
            result = conn.execute(
                sa.text("SELECT cf_scheduled_time FROM audit_events WHERE id = :id"),
                {"id": row_id},
            ).scalar_one()
        engine.dispose()
        assert result == epoch_ms


# ---------------------------------------------------------------------------
# Downgrade tests
# ---------------------------------------------------------------------------


class TestDowngrade:
    """LM-T0 downgrade reverses all changes."""

    def test_downgrade_restores_prev_rev(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        _run_alembic("downgrade", "-1")
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.connect() as conn:
            rev = conn.execute(
                sa.text("SELECT version_num FROM alembic_version")
            ).scalar_one()
        engine.dispose()
        assert rev == _PREV_REV

    def test_downgrade_removes_cf_scheduled_time(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        _run_alembic("downgrade", "-1")
        cols = _table_info(fixture_db, "audit_events")
        assert "cf_scheduled_time" not in cols

    def test_downgrade_narrows_changed_by(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        _run_alembic("downgrade", "-1")
        cols = _table_info(fixture_db, "audit_events")
        # After downgrade: VARCHAR(8), not VARCHAR(64)
        assert "64" not in cols["changed_by"]["type"].upper()

    def test_downgrade_restores_narrow_check(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        _run_alembic("downgrade", "-1")
        ddl = _table_ddl(fixture_db, "plaid_item")
        assert "pending_oauth" not in ddl
        assert "abandoned" not in ddl
        # Original values still present
        assert "active" in ddl
        assert "disconnected" in ddl

    def test_downgrade_refused_when_pending_oauth_exists(
        self, fixture_db: Path
    ) -> None:
        """Downgrade is refused if any plaid_item has status='pending_oauth'."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO plaid_item"
                    " (id, item_id, institution_id, institution_name,"
                    "  access_token_encrypted, status, created_at, updated_at)"
                    " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                    "  'tok_enc', 'pending_oauth', :now, :now)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "item_id": "item-block-po",
                    "now": _now(),
                },
            )
        engine.dispose()
        with pytest.raises(RuntimeError, match="refusing to downgrade"):
            _run_alembic("downgrade", "-1")

    def test_downgrade_refused_when_abandoned_exists(
        self, fixture_db: Path
    ) -> None:
        """Downgrade is refused if any plaid_item has status='abandoned'."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO plaid_item"
                    " (id, item_id, institution_id, institution_name,"
                    "  access_token_encrypted, status, created_at, updated_at)"
                    " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                    "  'tok_enc', 'abandoned', :now, :now)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "item_id": "item-block-ab",
                    "now": _now(),
                },
            )
        engine.dispose()
        with pytest.raises(RuntimeError, match="refusing to downgrade"):
            _run_alembic("downgrade", "-1")

    def test_downgrade_succeeds_when_only_original_statuses(
        self, fixture_db: Path
    ) -> None:
        """Downgrade proceeds when only 'active'/'disconnected' rows exist."""
        _run_alembic("upgrade", _THIS_REV)
        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.begin() as conn:
            conn.execute(
                sa.text(
                    "INSERT INTO plaid_item"
                    " (id, item_id, institution_id, institution_name,"
                    "  access_token_encrypted, status, created_at, updated_at)"
                    " VALUES (:id, :item_id, 'ins_test', 'Test Bank',"
                    "  'tok_enc', 'active', :now, :now)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "item_id": "item-ok-active",
                    "now": _now(),
                },
            )
        engine.dispose()
        _run_alembic("downgrade", "-1")

        engine2 = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine2.connect() as conn:
            rev = conn.execute(
                sa.text("SELECT version_num FROM alembic_version")
            ).scalar_one()
        engine2.dispose()
        assert rev == _PREV_REV


# ---------------------------------------------------------------------------
# Round-trip test
# ---------------------------------------------------------------------------


class TestRoundTrip:
    """Upgrade → downgrade → upgrade leaves schema consistent."""

    def test_round_trip(self, fixture_db: Path) -> None:
        _run_alembic("upgrade", _THIS_REV)
        _run_alembic("downgrade", "-1")
        _run_alembic("upgrade", _THIS_REV)

        cols = _table_info(fixture_db, "audit_events")
        assert "cf_scheduled_time" in cols
        assert "64" in cols["changed_by"]["type"].upper()

        ddl = _table_ddl(fixture_db, "plaid_item")
        assert "pending_oauth" in ddl
        assert "abandoned" in ddl

        engine = sa.create_engine(f"sqlite:///{fixture_db}")
        with engine.connect() as conn:
            rev = conn.execute(
                sa.text("SELECT version_num FROM alembic_version")
            ).scalar_one()
        engine.dispose()
        assert rev == _THIS_REV
