"""account_tag table

Revision ID: 0dfd3fb13224
Revises: 4545b7f3b8d3
Create Date: 2026-05-07 10:48:00.323923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfd3fb13224'
down_revision: Union[str, Sequence[str], None] = '4545b7f3b8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_tag',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'tag')
    )
    with op.batch_alter_table('account_tag', schema=None) as batch_op:
        batch_op.create_index('ix_account_tag_tag', ['tag'], unique=False)

    # NOTE: Same autogenerate-noise pattern as the prior phase3 migration —
    # transactions indexes flagged for removal because the model doesn't
    # declare them, but they exist in the live DB for performance. NOT
    # dropping. See 4545b7f3b8d3 for the same comment.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_account_tag_tag')

    op.drop_table('account_tag')
    # ### end Alembic commands ###
