"""initial schema

Revision ID: 1c8d9ab67214
Revises: 
Create Date: 2026-03-24 14:20:21.700565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8d9ab67214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.alter_column('old_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('new_value',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_events_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=36), nullable=True, comment='UUID of the Transaction that triggered this API call, if known'))
        batch_op.create_index(batch_op.f('ix_llm_usage_log_transaction_id'), ['transaction_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('source_hash',
               existing_type=sa.TEXT(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.TEXT(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.TEXT(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('currency_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=3),
               existing_nullable=True)
        batch_op.alter_column('amount_foreign',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('exchange_rate',
               existing_type=sa.TEXT(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('exchange_rate_source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('entity',
               existing_type=sa.TEXT(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.TEXT(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('tax_category',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('tax_subcategory',
               existing_type=sa.TEXT(length=32),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('deductible_pct',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(length=24),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'needs_review'"))
        batch_op.alter_column('confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('parent_id',
               existing_type=sa.TEXT(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('reimbursement_link',
               existing_type=sa.TEXT(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('payer_1099',
               existing_type=sa.TEXT(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('payer_1099_type',
               existing_type=sa.TEXT(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('attachments',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('raw_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('confirmed_by',
               existing_type=sa.TEXT(length=8),
               type_=sa.String(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'auto'"))
        batch_op.drop_index(batch_op.f('idx_transactions_date'))
        batch_op.drop_index(batch_op.f('idx_transactions_entity'))
        batch_op.drop_index(batch_op.f('idx_transactions_source_hash'))
        batch_op.drop_index(batch_op.f('idx_transactions_status'))
        batch_op.drop_index(batch_op.f('idx_transactions_tax_category'))
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source_hash'), ['source_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_tax_category'), ['tax_category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_tax_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_source_hash'))
        batch_op.drop_index(batch_op.f('ix_transactions_entity'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.create_index(batch_op.f('idx_transactions_tax_category'), ['tax_category'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_source_hash'), ['source_hash'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_date'), ['date'], unique=False)
        batch_op.alter_column('confirmed_by',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'auto'"))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('raw_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('attachments',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payer_1099_type',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(length=8),
               existing_nullable=True)
        batch_op.alter_column('payer_1099',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('reimbursement_link',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(length=36),
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(length=36),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=24),
               type_=sa.TEXT(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'needs_review'"))
        batch_op.alter_column('deductible_pct',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(1.0)'))
        batch_op.alter_column('tax_subcategory',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(length=32),
               existing_nullable=True)
        batch_op.alter_column('tax_category',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(length=32),
               existing_nullable=True)
        batch_op.alter_column('direction',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(length=16),
               existing_nullable=True)
        batch_op.alter_column('entity',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(length=16),
               existing_nullable=True)
        batch_op.alter_column('exchange_rate_source',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('exchange_rate',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('amount_foreign',
               existing_type=sa.Float(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('currency_code',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=False)
        batch_op.alter_column('source_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(length=64),
               existing_nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(length=255),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(length=32),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(length=36),
               existing_nullable=False)

    with op.batch_alter_table('llm_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_log_transaction_id'))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_changed_at'))
        batch_op.alter_column('new_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('old_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
