"""phase3 history tables

Revision ID: 4545b7f3b8d3
Revises: ceb6f498e2b1
Create Date: 2026-05-07 09:14:15.744601

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4545b7f3b8d3'
down_revision: str | Sequence[str] | None = 'ceb6f498e2b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_price',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='yfinance', nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    with op.batch_alter_table('historical_price', schema=None) as batch_op:
        batch_op.create_index('ix_historical_price_date', ['trade_date'], unique=False)

    op.create_table('account_balance_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('raw_account_name', sa.String(length=255), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'as_of', 'source', name='uq_acct_balance_snap_acct_date_src'),
    sa.UniqueConstraint('raw_account_name', 'as_of', 'source', name='uq_acct_balance_snap_rawname_date_src')
    )
    with op.batch_alter_table('account_balance_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_balance_snapshot_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_balance_snapshot_source_row_hash'), ['source_row_hash'], unique=False)
        batch_op.create_index('ix_acct_balance_snap_as_of', ['as_of'], unique=False)

    op.create_table('cost_basis_lot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('raw_account_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_name', sa.String(length=255), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_per_share', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wash_sale_adj', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_row_hash', name='uq_cost_basis_lot_row_hash')
    )
    with op.batch_alter_table('cost_basis_lot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_basis_lot_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_cost_basis_lot_symbol', ['symbol'], unique=False)

    op.create_table('expected_account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('last_4', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='unconfirmed', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_account_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed', 'unconfirmed')", name='ck_expected_account_status'),
    sa.ForeignKeyConstraint(['resolved_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution', 'account_name', 'last_4', name='uq_expected_account_natural_key')
    )
    with op.batch_alter_table('expected_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expected_account_resolved_account_id'), ['resolved_account_id'], unique=False)

    # NOTE: Autogenerate flagged transactions indexes (ix_transactions_direction,
    # ix_transactions_entity_date, ix_transactions_parent_id, ix_transactions_source)
    # for removal because the current Transaction model does not declare them via
    # Index() or index=True. They exist in the live DB for performance and were
    # likely added in a prior migration. Intentionally NOT dropping — schema drift
    # outside Phase 3 scope.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No corresponding restore — see upgrade() note about transactions indexes.

    with op.batch_alter_table('expected_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expected_account_resolved_account_id'))

    op.drop_table('expected_account')
    with op.batch_alter_table('cost_basis_lot', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_basis_lot_symbol')
        batch_op.drop_index(batch_op.f('ix_cost_basis_lot_account_id'))

    op.drop_table('cost_basis_lot')
    with op.batch_alter_table('account_balance_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_acct_balance_snap_as_of')
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshot_source_row_hash'))
        batch_op.drop_index(batch_op.f('ix_account_balance_snapshot_account_id'))

    op.drop_table('account_balance_snapshot')
    with op.batch_alter_table('historical_price', schema=None) as batch_op:
        batch_op.drop_index('ix_historical_price_date')

    op.drop_table('historical_price')
    # ### end Alembic commands ###
