"""add payment link and send tracking columns to invoices

Revision ID: 4cbdb23e658f
Revises: d4835f9da609
Create Date: 2026-04-24 13:38:21.097956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cbdb23e658f'
down_revision: Union[str, Sequence[str], None] = 'd4835f9da609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_link_url', sa.String(length=512), nullable=True, comment='Stripe payment link URL for online payment'))
        batch_op.add_column(sa.Column('payment_link_id', sa.String(length=255), nullable=True, comment='Stripe payment link ID (for deactivation on void)'))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True, comment='When the invoice email was last sent'))
        batch_op.add_column(sa.Column('sent_to', sa.String(length=255), nullable=True, comment='Email address the invoice was sent to'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('sent_to')
        batch_op.drop_column('sent_at')
        batch_op.drop_column('payment_link_id')
        batch_op.drop_column('payment_link_url')

    # ### end Alembic commands ###
