"""add_planning_runs_table

Revision ID: 63c79e8be034
Revises: 0d372cdb13df
Create Date: 2026-06-02 00:30:25.345545

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '63c79e8be034'
down_revision: str | Sequence[str] | None = '0d372cdb13df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('live_inputs_json', sa.JSON(), nullable=False),
    sa.Column('scenarios_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planning_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planning_runs_run_at'), ['run_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planning_runs_run_at'))

    op.drop_table('planning_runs')
    # ### end Alembic commands ###
