"""float to decimal for currency fields

Revision ID: 9cc511c9b845
Revises: a2ad1082b755
Create Date: 2026-03-24 14:24:26.893172

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9cc511c9b845'
down_revision: str | Sequence[str] | None = 'a2ad1082b755'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
