"""add brokerage tables

Revision ID: ceb6f498e2b1
Revises: 4cbdb23e658f
Create Date: 2026-05-06 09:01:15.425139

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ceb6f498e2b1'
down_revision: str | Sequence[str] | None = '4cbdb23e658f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('account_type', sa.String(length=24), nullable=False),
    sa.Column('entity', sa.String(length=16), nullable=False),
    sa.Column('tax_sheltered', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('parent_account_id', sa.String(length=36), nullable=True, comment='Self-FK: BrokerageLink → MS 401k plan wrapper'),
    sa.Column('is_plan_wrapper', sa.Boolean(), server_default='0', nullable=False, comment='True for plan-only accounts whose transactions should not flow to P&L'),
    sa.Column('beneficiary', sa.String(length=64), nullable=True, comment="Free-text — e.g. 'Aiden', 'Emerson'"),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_type IN ('taxable', 'joint', 'roth_ira', 'trad_ira', '401k', '403b', 'hsa', '529', 'tod', 'brokeragelink', 'rsu')", name='ck_account_type'),
    sa.CheckConstraint("broker IN ('etrade', 'schwab', 'vanguard', 'fidelity')", name='ck_account_broker'),
    sa.CheckConstraint("entity IN ('sparkry', 'blackline', 'personal')", name='ck_account_entity'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'account_number', name='uq_account_broker_number')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_broker'), ['broker'], unique=False)

    op.create_table('brokerage_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False, comment='Broker-native action string'),
    sa.Column('canonical_action', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('cusip', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Signed: positive = cash in, negative = cash out'),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('paired_transaction_id', sa.String(length=36), nullable=True, comment='Links dividend ↔ reinvest pair'),
    sa.Column('is_synthetic', sa.Boolean(), server_default='0', nullable=False, comment='True if this row was synthesized (e.g. E*TRADE single-row reinvest dividend partner)'),
    sa.Column('status', sa.String(length=16), server_default='imported', nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("canonical_action IN ('buy', 'sell', 'dividend_qualified', 'dividend_ordinary', 'interest', 'reinvest', 'capital_gain_lt', 'capital_gain_st', 'rsu_vest', 'stock_split', 'cash_in_lieu', 'sweep', 'exchange', 'transfer', 'contribution', 'distribution', 'fee', 'journal', 'valuation_adjustment', 'other')", name='ck_brokerage_tx_canonical_action'),
    sa.CheckConstraint("status IN ('imported', 'confirmed', 'rejected')", name='ck_brokerage_tx_status'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['paired_transaction_id'], ['brokerage_transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source_row_hash', name='uq_brokerage_tx_dedup')
    )
    with op.batch_alter_table('brokerage_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_canonical_action'), ['canonical_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_source_row_hash'), ['source_row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_brokerage_transaction_trade_date'), ['trade_date'], unique=False)

    op.create_table('position_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('avg_cost_basis', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('unrealized_gain', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source_row_hash', name='uq_position_snapshot_dedup')
    )
    with op.batch_alter_table('position_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_snapshot_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshot_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshot_source_row_hash'), ['source_row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshot_symbol'), ['symbol'], unique=False)

    op.create_table('realized_gain_loss',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unadjusted_cost_basis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('gain_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('lt_gain_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('st_gain_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('term', sa.String(length=8), nullable=True),
    sa.Column('wash_sale', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('disallowed_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_row_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("term IN ('short', 'long') OR term IS NULL", name='ck_realized_gl_term'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source_row_hash', name='uq_realized_gl_dedup')
    )
    with op.batch_alter_table('realized_gain_loss', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_realized_gain_loss_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_realized_gain_loss_closed_date'), ['closed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_realized_gain_loss_source_row_hash'), ['source_row_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_realized_gain_loss_symbol'), ['symbol'], unique=False)

    # NOTE: Autogenerate also reported spurious "drop_index" ops on the
    # transactions table (ix_transactions_direction/entity_date/parent_id/source)
    # because those indexes exist in the live DB but were dropped from the model
    # at some point. Removed from this migration — that drift is unrelated to
    # brokerage-table introduction and should be reconciled in a separate change.

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('realized_gain_loss', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_realized_gain_loss_symbol'))
        batch_op.drop_index(batch_op.f('ix_realized_gain_loss_source_row_hash'))
        batch_op.drop_index(batch_op.f('ix_realized_gain_loss_closed_date'))
        batch_op.drop_index(batch_op.f('ix_realized_gain_loss_account_id'))

    op.drop_table('realized_gain_loss')
    with op.batch_alter_table('position_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_snapshot_symbol'))
        batch_op.drop_index(batch_op.f('ix_position_snapshot_source_row_hash'))
        batch_op.drop_index(batch_op.f('ix_position_snapshot_as_of'))
        batch_op.drop_index(batch_op.f('ix_position_snapshot_account_id'))

    op.drop_table('position_snapshot')
    with op.batch_alter_table('brokerage_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_trade_date'))
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_symbol'))
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_status'))
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_source_row_hash'))
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_canonical_action'))
        batch_op.drop_index(batch_op.f('ix_brokerage_transaction_account_id'))

    op.drop_table('brokerage_transaction')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_broker'))
        batch_op.drop_index(batch_op.f('ix_account_account_number'))

    op.drop_table('account')
    # ### end Alembic commands ###
