"""add tax_documents table

Revision ID: d4835f9da609
Revises: 4707b428aea1
Create Date: 2026-03-26 01:15:30.737230

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4835f9da609'
down_revision: str | Sequence[str] | None = '4707b428aea1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False, comment='Tax year, e.g. 2025'),
    sa.Column('form_type', sa.String(length=16), nullable=False, comment='TaxFormType enum value'),
    sa.Column('entity', sa.String(length=16), nullable=False, comment='Entity enum value: sparkry | blackline | personal'),
    sa.Column('payer_name', sa.String(length=255), nullable=False, comment="e.g. 'FC International Education LLC'"),
    sa.Column('payer_ein', sa.String(length=10), nullable=True, comment="e.g. '85-1499443'"),
    sa.Column('recipient_name', sa.String(length=255), nullable=False, comment="e.g. 'Travis Sparks'"),
    sa.Column('recipient_tin_last4', sa.String(length=4), nullable=True, comment='Last 4 of SSN/EIN for verification'),
    sa.Column('amounts', sa.JSON(), nullable=False, comment='Form-specific box values keyed by box name'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Primary/headline amount (form-type-specific primary box)'),
    sa.Column('source_file', sa.Text(), nullable=True, comment='Relative path from project root, e.g. data/tax-docs/2025/personal/...'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='TaxDocumentStatus enum value'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Free-form notes'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("entity IN ('sparkry', 'blackline', 'personal')", name='ck_tax_document_entity'),
    sa.CheckConstraint("form_type IN ('1099-NEC', '1099-INT', '1099-DIV', '1099-B', '1099-K', 'K-1', '1098', 'PROPERTY_TAX', 'OTHER')", name='ck_tax_document_form_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_tax_document_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_year', 'form_type', 'entity', 'payer_ein', name='uq_tax_doc_natural_key')
    )
    with op.batch_alter_table('tax_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_documents_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_documents_tax_year'), ['tax_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_documents_tax_year'))
        batch_op.drop_index(batch_op.f('ix_tax_documents_entity'))

    op.drop_table('tax_documents')
    # ### end Alembic commands ###
